### ISSUE TITLE
Calling tearDown() throws an unhandled exception

### ISSUE THREAD

**Issue by conqueror404** [onfido/onfido-sdk-ui#1325] opened 2021-02-03 10:02 UTC
### What was the expected behaviour?

Calling the `tearDown()` function on the object returned by onfido `init()` should result in proper teardown of the SDK.

### What happened instead?

The call fails with:

`Unhandled Rejection (TypeError): Object(...) is not a function`

### Version info:

- Onfido SDK - >=6.3.0
- OS - macOS 10.15.7
- Browser - Firefox, Chrome latest versions

### Integration configuration:

Barebone integration, default options, the only options we override are `useModal: true` and `isModalOpen:true` on `init()`.

### Steps to reproduce:

After calling `init()` the modal is open, then by manually closing the modal and the subsequent call to `.setOptions({ isModalOpen: false })` if we call the `tearDown` function it throws the exception above.

### Note:
It works as expected using an Onfido SDK version < 6.3.0.

**Comment by andra-radu** [comment] 2021-02-03 12:11
Hi @conqueror404,

Would it be possible to please share with us your integration configuration?

Thank you,
Andra

**Comment by conqueror404** [comment] 2021-02-03 13:25
Hi Andra,

Thanks for your quick reply, here is a small code sample. 
All I did was promisify and wrap your utility with a class.

```
class OnfidoSdkHandler {
...
async openModal(
    containerId: string,
  ): Promise<OnfidoOpenModalResolve> {
    this.destroy()

    return new Promise(res => {
      this.onfidoHandler = init({
        token: this.token,
        containerId,
        useModal: true,
        isModalOpen: true,
        onModalRequestClose: () => {
          res({ type: 'success', action: 'modal_request_close' })
        },
        onComplete: (data: OnfidoResponse) => {
          res({ type: 'success', action: 'completed', data })
        },
        onError: (ex: OnfidoException) => {
          res({ type: 'error', exception: ex })
        },
      })
    })
  }

  closeModal() {
    if (this.onfidoHandler) {
      this.onfidoHandler.setOptions({ isModalOpen: false })
    }
  }
  destroy() {
    if (this.onfidoHandler) {
      this.onfidoHandler.tearDown()
    }
  }
}
```

When a user opens the modal for the first time and they manually close it, `openModal()` is called followed by `closeModal()`. Then when the user tries to open the modal for the second time, there is a previous SDK instance to destroy(kept at the class level), so calling `tearDown()` on the onfido handler should work. Unfortunately it seems to fail with:

```
Unhandled Rejection (TypeError): Object(...) is not a function
```

Moreover I can replicate the same unhandled exception by simply putting a `setTimeout()` and tearing everything down after 10 seconds, without other user interaction besides opening the modal.

This used to work in prior versions of Onfido SDK(`<6.3.0`).

**Comment by conqueror404** [comment] 2021-02-03 13:45
I wanted to add that I am using `react@16.9` but it shouldn't make any difference.

**Comment by kopijunkie** [comment] 2021-02-08 18:28
Hi @conqueror404 

Yes, the React version shouldn't make a difference. We did happen to make a couple of internal changes, namely upgrade from Preact v8 to v10 in v6.3.0 and replace `react-modal-onfido` with version `3.11.2` of `react-modal` which I believe is what caused the call to `tearDown()` to not work for your implementation since upgrading to that version upwards.

I was able to reproduce it but will need to look further into this for now.

**Comment by JohnathanWhite** [comment] 2021-02-11 21:51
hey @kopijunkie. I am also getting the same error on teardown.

**Comment by kopijunkie** [comment] 2021-02-24 17:11
Hi @JohnathanWhite is your integration similar to the configuration with the same version of the SDK and/or setup shared above also, asking so we know what type of integrations this is affecting? 

I've created a ticket internally for us to investigate this further so that we can find a solution for it or get it fixed in the meantime.

**Comment by andra-radu** [comment] 2021-06-08 07:58
Hi @conqueror404 @JohnathanWhite The fix was released. Could you please check from your side and let us know if you are encountering any further issues?

**Comment by JohnathanWhite** [comment] 2021-06-15 14:24
@andra-radu I see that the fix was merged into development. When will this be available on master?

**Comment by andra-radu** [comment] 2021-06-15 14:40
@JohnathanWhite Our SDK team is hoping to be able to release 6.10.0 by end of the week.

**Comment by andra-radu** [comment] 2021-06-22 14:06
@JohnathanWhite 6.10.0 was released this morning.

**Comment by JohnathanWhite** [comment] 2021-06-23 13:47
@andra-radu issue is resolved thank you!

**Closed** 2021-06-23 14:24 UTC
Labels: bug
