### ISSUE TITLE
[iOS] User receives file type not supported error after record confirmation 

### ISSUE THREAD

**Issue by Excello** [onfido/onfido-sdk-ui#1465] opened 2021-06-01 13:53 UTC
### What was the expected behaviour?

User should see success screen after confirmation of the record 

### What happened instead?

User receives file type not supported error after record confirmation 

### Version info:

Onfido SDK: onfido-sdk-ui 6.4.0
OS: iOs 14.4
Browser: Chrome/Safari for iOS
Device: iPhone 12 Pro
Framework or relevant dependencies (if applicable): ReactJS.

### Integration configuration:

```
useMemoryHistory: true,
token,
onComplete,
steps: [
  {
    type: 'document',
    options: {
      documentTypes: {
        driving_licence: false,
        passport: true,
        national_identity_card: true,
        residence_permit: false
      },
      forceCrossDevice: true,
    }
  },
  {
    type: 'face',
    options: {
      requestedVariant: 'video',
      uploadFallback: false,
    }
  },
]
```

### Steps to reproduce:

1) Generate link
2) Open it on mobile in Chrome or Safari browser
3) Capture document (e.g. Passport)
4) Enable camera permissions 
5) Record a video
6) Click confirm on record confirmation screen

### Demo:
N/A

![image0](https://user-images.githubusercontent.com/26041295/120335434-2303db80-c2fa-11eb-8502-507eb3cf2dc1.jpeg)

**Comment by Excello** [comment] 2021-06-01 14:06
Record
https://user-images.githubusercontent.com/26041295/120337114-b25dbe80-c2fb-11eb-8acb-f502919fadc5.mov

**Comment by Excello** [comment] 2021-06-01 14:53
URL: https://api.onfido.com/v3/live_videos
Status: 422

Request: 
```
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: video/mp4


------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="languages"

[{"source":"sdk","language_code":"en_US"}]
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="challenge"

[{"query":[9,8,1],"type":"recite"},{"query":"turnLeft","type":"movement"}]
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="challenge_id"

1tLqdKnNbxzNtrpD8nCedqK05jf
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="challenge_switch_at"

694
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="sdk_metadata"

{"captureMethod":"live","camera_name":"Front Camera","microphone_name":"iPhone Microphone","isCrossDeviceFlow":true,"deviceType":"mobile","system":{"os":"iPhone","os_version":"14.4.2","browser":"Safari","browser_version":"14.0.3"}}
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="sdk_source"

onfido_web_sdk
------WebKitFormBoundarySfUBorBAUN58CpLZ
Content-Disposition: form-data; name="sdk_version"

6.4.0
------WebKitFormBoundarySfUBorBAUN58CpLZ--
```

Response:

```
{
    "error": {
        "type": "validation_error",
        "message": "There was a validation error on this request",
        "fields": {
            "attachment_content_type": [
                "unsupported mime type"
            ],
            "attachment": [
                "unsupported mime type"
            ]
        }
    }
}
```

**Comment by Excello** [comment] 2021-06-01 14:53
Two days ago it was okay with this functionality

**Comment by lastavenka** [comment] 2021-06-01 14:54
We have the same issue.

**Comment by ryanduan-fi** [comment] 2021-06-01 15:24
Having the same issue

**Comment by kopijunkie** [comment] 2021-06-01 15:28
Hi @Excello 

Thank you for raising this issue and all the information provided. We are currently investigating this to find out why it is happening. I'll update once we have a solution in place.

**Comment by kopijunkie** [comment] 2021-06-01 16:16
We've identified the cause and are now working on a hotfix for this on our back end service.

**Comment by ryanduan-fi** [comment] 2021-06-01 18:25
Hi @kopijunkie  any idea when the hotfix will be deployed?

**Comment by dnlserrano** [comment] 2021-06-01 18:26
We're working on it, sorry for the delay @ryanduan-fi.

**Comment by ryanduan-fi** [comment] 2021-06-01 18:27
@dnlserrano No worries thanks for the update!

**Comment by dnlserrano** [comment] 2021-06-01 19:39
We'll be ready to ship a fix soon (hopefully next 30 minutes). 🤞

**Comment by dnlserrano** [comment] 2021-06-01 20:27
Can you please check if it works now? It should be fixed according to our metrics.

**Comment by Excello** [comment] 2021-06-02 07:26
Verified on our intergration and all looks good. Thanks!

**Comment by dnlserrano** [comment] 2021-06-02 08:18
Thank you! We will be posting a [post-mortem soon](https://status.onfido.com/incidents/ck9qgl0r1ghx).

**Closed by dnlserrano** 2021-06-02 08:18 UTC
Labels: bug
