### ISSUE TITLE
Blank page localbitcoins.com

### ISSUE THREAD

**Issue by amoyano** [onfido/onfido-sdk-ui#993] opened 2020-05-08 14:12 UTC
Hi i'm having this issue too, is it resolved?  whe I try with my laptop
And when I try with my iphone last version safari and chrome  said
UNSUPPORTED BROWSER, restar tthe process with the last version....

iOS: 13.4.1
thanks

**Comment by ramprasad-parajuli** [comment] 2020-05-08 20:46
Hi @amoyano thank you for your message.
Are you experiencing the issue "UNSUPPORTED BROWSER, restart the process with the last version" when you try to complete the flow on a safari browser?
You are getting the error message on the chrome browser in an iOS device when trying to capture a liveness video because of the "uploadfallback=false" feature in your configuration code. ​​
![image](https://user-images.githubusercontent.com/45214564/81447819-2c8c3580-9132-11ea-97ad-e90fcb29b592.png)

There is an issue/bug on the iOS device's chrome and firefox browsers where it does not routes the face verification step to selfie if the above feature is used. If the mobile device does not have a camera or there is no camera browser support, and uploadFallback is set to false, the user will not be able to complete the flow.
As the issue is on Chrome (Google/Apple) side, I am afraid we do not have much control over it, and for that reason, we made a change in our error message where we ask the user to make use of the Safari browser instead to complete the flow.

**Comment by ctrlaltdylan** [comment] 2020-05-11 13:28
Reporting that I have a very high volume of users reporting they're having this issue as well.

**Comment by kopijunkie** [comment] 2020-05-11 16:07
Thank you for raising this issue @amoyano @ctrlaltdylan 

We've identified it happening with integrations that have disabled `uploadFallback` and are currently working on a fix for users on iOS 13.4.1 and workaround would be to enable it for now.

**Comment by amoyano** [comment] 2020-05-11 16:11
Thank you!
Agustín Moyano
*Ingeniero en Sistemas *
Cel: 0297-154614367
[image: email] <moyanoa@gmail.com>
<http://www.companysig.com/>

**Comment by ctrlaltdylan** [comment] 2020-05-15 12:32
@kopijunkie we've enabled it but have gotten at least 1 more case of "unsupported browser" error from a customer.

Could we keep this issue open until the actual fix is released so we know if we should update our SDKs for the fix?

**Comment by kopijunkie** [comment] 2020-05-15 13:17
@ctrlaltdylan Sorry about that. Looks like this ticket got auto closed when the PR was merged. I've replied on your ticket (which is still open) but we have released the patch fix for it in [5.9.1](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.9.1)

**Comment by kopijunkie** [comment] 2020-05-15 13:18
@amoyano Could you let us know if you are still experiencing issues after updating to 5.9.1?

**Comment by anttilbc** [comment] 2020-05-26 09:39
We are still having several users reporting blank page after uploading documents. We have updated to 5.9.2

**Comment by stefaniacardenas** [comment] 2020-05-26 17:29
@anttilbc your problem seems different from the one reported in this issue. This issue seems similar to the one described [here](https://github.com/onfido/onfido-sdk-ui/issues/979). Is it what you are experiencing? If so, please add more details inside that issue or create a new one to help us understand how to reproduce the issue. Please include device OS and browser OS too. Many thanks

**Comment by stefaniacardenas** [comment] 2020-06-05 11:56
I'm going to close this issue because the bug on Safari on iOS 13.4.1 has been fixed in version 5.9.2. Please be aware that there is still a pending fix for [this issue](https://github.com/onfido/onfido-sdk-ui/issues/1030) that will go live in the next release.

**Closed by stefaniacardenas** 2020-06-05 11:56 UTC
Labels: bug
