### ISSUE TITLE
[Question] Can the onComplete callback be called with partial data?

### ISSUE THREAD

**Issue by undergroundquizscene** [onfido/onfido-sdk-ui#973] opened 2020-04-24 08:52 UTC
I’m using this at work, and we're finding that the `onComplete` callback is sometimes being called with an empty object, or an object without the `face` key. Is this deliberate? Assuming so, is there any documentation of what it means when this happens (e.g. that something has gone wrong, or that there was nothing to do)?

**Comment by stefaniacardenas** [comment] 2020-04-27 16:14
Hi @undergroundquizscene, which version of the SDK are you using? If you have requested both `document` and `face` step then the `onComplete` callback should include both keys

**Comment by timparker87** [comment] 2020-04-30 13:35
hello there - we're also seeing this issue with our integration. In our case, it seems to be just iOS devices that have this problem, and although the `document_front` key is there, it is `undefined`.

We're on `onfido-sdk-ui@^5.8.0`

![image (1)](https://user-images.githubusercontent.com/20547286/80715785-bf9fec80-8aee-11ea-9a50-62ebb0b77593.png)
![image (2)](https://user-images.githubusercontent.com/20547286/80715788-c0d11980-8aee-11ea-8b1e-58a024166040.png)

any ideas or advice greatly appreciated @stefaniacardenas 🙂

**Comment by timparker87** [comment] 2020-04-30 14:17
Just as a bit more info - we can recreate this quite reliably on iOS (but it doesn't happen 100% of the time). We tried updating to `onfido-sdk-ui@^5.9.0` but same behaviour.

We are not seeing any errors in the `onError` handler.

Happy to share more details of our setup, but it's a fairly simple integration with `welcome`, `document` & `complete`.

Haven't been able to recreate this issue on none iOS devices - they seem to be fine.

**Comment by kopijunkie** [comment] 2020-05-04 17:04
Hi @timparker87 

Could you provide us with the configuration used to initialise the SDK with and the framework you're using, if any? Those details could provide some further insight on our end.

I haven't been able to replicate it locally with our demo app but I did get a TypeError at `onComplete` on the integration link you've provided via ZenDesk when viewing from an iOS device. Feel free to continue the conversation there instead if you prefer.

**Comment by timparker87** [comment] 2020-05-05 11:20
Hi @kopijunkie :)

Thanks for the response, here is our configuration to initialise the SDK:

```
init({
  useModal: false,
  token: this.state.jwt,
  onComplete: (data) => {
    this.props.updatePerson({
      person: {
        onfido_document_id_1: data.document_front.id,
        onfido_document_id_2: data.document_back ? data.document_back.id : null,
        ...this.props.person,
      },
    });
  },
  steps: [
    {
      type: 'welcome',
      options: {
        title: "Sample",
        descriptions: ["Sample"],
      },
    },
   {
      type: 'document',
      options: {
        documentTypes: {
          passport: true,
          driving_licence: this.props.locale === 'new-york',
        },
      },
    },
    'complete',
  ],
})
```

We are using the SDK from React.

**Comment by undergroundquizscene** [comment] 2020-05-05 14:41
Sorry for the delay in replying! We have forked the library in order to apply the fix that was suggested [in another issue](https://github.com/onfido/onfido-sdk-ui/issues/707#issuecomment-508101134). Our fork was at version 5.5, but I have just updated it to the latest master – I will let you know if the problem continues.

We are calling the SDK from purescript, while using React.

**Comment by raldred** [comment] 2020-05-05 14:50
That is interesting, we're also using React, along with react-router-dom's BrowserRouter which uses the History API throughout our app for navigation.

**Comment by kopijunkie** [comment] 2020-05-07 13:47
@undergroundquizscene Thanks for your reply. Just to confirm, did the fix you applied on your fork resolve the issue you were experiencing? 
There is a known issue with unexpected behaviour with the back navigation within the SDK clashing with some host apps as brought up in the issue you linked. That's on our backlog but it would be good to know if this is something we need to look out for also when fixing.

**Comment by timparker87** [comment] 2020-05-12 13:32
Hi @kopijunkie yes we are - we are using react-router-dom's BrowserRouter

**Comment by undergroundquizscene** [comment] 2020-05-13 09:18
> @undergroundquizscene Thanks for your reply. Just to confirm, did the fix you applied on your fork resolve the issue you were experiencing?
> There is a known issue with unexpected behaviour with the back navigation within the SDK clashing with some host apps as brought up in the issue you linked. That's on our backlog but it would be good to know if this is something we need to look out for also when fixing.

@kopijunkie Sorry, to be clearer: The fix applied on the fork was applied a few months ago, before our current issue started popping up. In response to the current issue I updated our fork from version 5.5 to master, and that appears to have fixed this issue.

**Comment by kopijunkie** [comment] 2020-05-14 13:51
@undergroundquizscene Thanks for clarifying. I'll close this ticket then. 

@timparker87 Still looking into your issue, as it seems to be a slightly different case and device specific. Will continue conversation with you on Zendesk once I have an update or need further info.

**Closed by kopijunkie** 2020-05-14 13:51 UTC
