### ISSUE TITLE
Connection lost error shows up when uploading ID card

### ISSUE THREAD

**Issue by tcthachlpit94** [onfido/onfido-sdk-ui#851] opened 2019-11-05 10:29 UTC
**Version: ^5.2.1**

We are facing the problem that `Connection lost` error shows up eventually.
Please check following screenshot.

![image (2)](https://user-images.githubusercontent.com/17648255/68199668-0eae0e80-fff1-11e9-8057-c62d02b72989.png)

**Comment by stefaniacardenas** [comment] 2019-11-05 16:36
Hi, in order to debug this I would need some more information. What are the steps to reproduce it? What does your configuration look like? How are you creating the SDK token? In which browser/device are you seeing this issue? Thank you

**Comment by tcthachlpit94** [comment] 2019-11-06 02:59
@stefaniacardenas 
Sorry, following is our configuration:
```
{
  token,
  containerId: 'onfido-mount',
  steps: [
    {
      type: 'document',
      options: {
        documentTypes: {
          passport: false,
          driving_licence: false,
          national_identity_card: true,
        },
      },
    },
    {
      type: 'face',
      options: {
        uploadFallback: false,
      },
    },
  ],
  userDetails: { smsNumber },
  onComplete: async (message, submessage) => {
  // we call our server to perform a check...
},
```
**Browser:** Safari on iOS

Honestly we can not reproduce this issue on our side but our customers do see this problem sometimes then we got some reports. This bugs occurs for a minority of our users.
We use fullstory to check on a specific user and see that she run into this problem right after uploading ID card photo. 

Thank you for your support.

**Comment by stefaniacardenas** [comment] 2019-11-13 16:42
Hi @tcthachlpit94, sorry for the late reply. I must have missed your message. Do you have any visibility on when she started the flow? Was the token within its expiration time (90 minutes)?

**Comment by tcthachlpit94** [comment] 2019-11-14 04:38
Hello @stefaniacardenas 
Here is our flow of integrating with Onfido.

# Technical flow:

The front-end asks an applicant token to our backend (`POST /onfido/token`). Our backend creates an Applicant profile on Onfido's server and returns the Applicant ID (token) to the front-end. The front-end uses it to initialise the JS SDK.

When the user uses the JS SDK, it uploads the identity card and the selfie directly to Onfido's servers. Not to our backend. But, when the user completed all the steps, we send a call to our backend (`POST /onfido/checks`) to notify that the users uploaded the document and the selfie.

Then, the back-end calls Onfido API to retrieve and store locally the identity card and the selfie on our dashboard. Then, it performs a check asking for a `Document` and `Facial Similarity` report.

Few minutes later, Onfido calls our API to notify us that the reports are ready. So our back-end use Onfido API to get the reports. 

The issue happens in uploading identity card step. But it is weird and minority. 
We can provide you the full-story in a private channel.
Hope that will help you. Thank you.

**Comment by stefaniacardenas** [comment] 2019-11-14 11:45
Hi @tcthachlpit94, thanks for the detailed explanation. From the information provided, it looks like there is nothing wrong with your integration. Feel free to get in touch with more details on api@onfido.com. I will close this issue as unreproducible, but our team can follow up via our private channel.

**Closed by stefaniacardenas** 2019-11-14 11:45 UTC
