### ISSUE TITLE
No camera detected for the selfie step

### ISSUE THREAD

**Issue by antoinelame** [onfido/onfido-sdk-ui#722] opened 2019-07-08 03:16 UTC
Hello,

On mobile, we are facing a bug during the selfie step. The user is not able to use his camera to take the selfie, even if he has already used it just before to take a picture of his ID card.

1. **Document Step**
The user is able to use his phone to take pictures (front and back sides).

2. **Selfie Step**
The user is not able to take a picture and get [this message](https://i.imgur.com/2OZ5kNU.png): _« No camera detected. Restart the process with a different device »_.

This bug occurs when we set `uploadFallback` to `false`.

```js
steps: [
  {
    type: 'document',
    options: {
      documentTypes: {
        passport: false,
        driving_licence: false,
        national_identity_card: true,
      },
    },
  },
  {
    type: 'face',
    options: {
      uploadFallback: false,
    },
  },
],
```

We use the 5.1.0 version.

**Comment by stefaniacardenas** [comment] 2019-07-08 15:53
Hi @antoinelame, there is an important distinction to be made regarding the way camera works on `document` step vs `face` step.

The `document` steps uses the native camera mode. That means that when you click on "Take photo" you are using the camera app on your phone. In some browsers that might allow the user to select an image from their gallery if they want to.

The `face` step instead embeds the camera inside the browser. The browser requests permissions to the user via `getUserMedia`, then takes a video or photo depending on the variant you've requested.
When the browser does not support embedding the webcam (because of lack of API support or missing functionalities) we fallback to the native camera mode. As mentioned earlier, this can lead to gallery access. 

Some of our customer have strict requirements for which their users should never be allowed to upload images from the gallery, therefore we have introduced this flag `uploadFallback: false`. 
As stated in the documentation, you should be careful when using this feature as it might lead to user drop-off.
> Warning: [...] If the mobile does not have a camera or there is no camera browser support, and the uploadFallback is set to false, **the user won't be able to complete the flow**.

**Comment by ctrlaltdylan** [comment] 2019-07-08 18:09
> When the browser does not support embedding the webcam (because of lack of API support or missing functionalities) we fallback to the native camera mode. As mentioned earlier, this can lead to gallery access.

Thanks @stefaniacardenas this makes sense why this display screen occurs.

However, instead of just showing this dead end screen; why can't you instead allow the user to attempt to switch to another device like their mobile phone by displaying the SMS phone input option?

The current "dead end" is a poor experience for our users.

In the past few months we've had multiple cases where fraudsters were able to upload a selfie ripped from social media and Onfido passed them. So we need this `uploadFallback: false` option set because file uploads for selfies in particular are easier to fool your ML algos.

If the user's browser doesn't support embedding the webcam - then why not allow the user to switch to another device and continue the flow?

**Comment by antoinelame** [comment] 2019-07-09 02:03
@stefaniacardenas Thank you for these explanations. Could we get a list of supported browsers?

**Comment by antoinelame** [comment] 2019-07-09 09:31
Thank you @stefaniacardenas for these explanations. So from what I understand, when `uploadFallback` is disabled, the selfie capture will work only if the browser supports `getUserMedia`.

I checked the support table for this API and it's [pretty well supported](https://caniuse.com/#feat=stream): at least on all latest versions of most used browsers.

But I get the error _« No camera detected »_ on:
- Safari 12.1 (iOS)
- Chrome 75 (iOS)

... even if both of theses versions support `getUserMedia`.
I also checked that Safari and Chrome have the iOS permissions to access to the camera.

So, given that my browsers support the API, is it a bug?

**Comment by stefaniacardenas** [comment] 2019-07-09 10:41
Hi @ctrlaltdylan, thank you so much for your feedback. It's in our roadmap to improve this part of the flow. I will speak with the rest of the team to prioritise a solution for this issue. I will post more update here.

Hi @antoinelame, for the selfie option the camera can be embedded in all browsers that support `getUserMedia`. According to [caniuse](https://caniuse.com/#search=getusermedia) the only major browser that does not support `getUserMedia` is IE11. In reality, Chrome for iOS, which is built on top . of the iOS WebKit rendering engine, does not support `getUserMedia` either. See bug chromium [here](https://bugs.chromium.org/p/chromium/issues/detail?id=752458)

For the `video` option the camera can be embedded in all browsers that support MediaRecorder API. That is Chrome, Firefox and Samsung Internet. There is no support on Safari, Edge and IE11. Full caniuse list [here](https://caniuse.com/#search=mediarecorder).

I just tested on Safari 12.1 and it's working as expected on our demo app. 
Do you see "No camera detected" also on Safari or is it a different error? Is Safari enabled to use the camera at OS level? 
Are you able to use the camera in Safari on this [demo](https://webrtc.github.io/samples/src/content/getusermedia/canvas/)?

**Comment by antoinelame** [comment] 2019-07-09 10:53
Hi @stefaniacardenas,

>  In reality, Chrome for iOS, which is built on top of the iOS WebKit rendering engine, does not support getUserMedia either.

Ok, I see, and what about Chrome for Android?

> Do you see "No camera detected" also on Safari or is it a different error? Is Safari enabled to use the camera at OS level?
Are you able to use the camera in Safari on this demo?

At the OS level, Safari has the permission to access the camera: _« Camera & Microphone Access: enabled »_.

Yes, on our website, we see _« No camera detected »_ when I use Safari 12.1 (iOS). It's exactly the same message as on my first screenshot.

I tried your demo with Safari 12.1 (iOS) and it works well. First I have a pop-up to ask for the camera permission, and then I can see on the page my camera recording.

**Comment by stefaniacardenas** [comment] 2019-07-09 12:04
Chrome for Android supports `getUserMedia`.
>I tried your demo with Safari 12.1 (iOS) and it works well.

For clarity, the demo I sent you earlier is from https://webrtc.github.io/samples, it's not an Onfido one.
I tested on our [demo app](https://5-1-0-tag-onfido-sdk-ui-onfido.surge.sh/?uploadFallback=false) and I cannot reproduce the issue. Which iPhone are you testing on?

**Comment by antoinelame** [comment] 2019-07-09 13:14
I tested your Onfido demo and it works with Safari 12.1 on my iPhone 7.
I don't get why it's not working on our website.

We use the `5.1.0` version and here is our configuration:

```js
{
  token,
  containerId: 'onfido-mount',
  language: {
    // ...
  },
  steps: [{
      type: 'document',
      options: {
        documentTypes: {
          passport: false,
          driving_licence: false,
          national_identity_card: true,
        },
      },
    },
    {
      type: 'face',
      options: {
        uploadFallback: false,
      },
    },
  ],
  userDetails: {
    smsNumber
  },
  onComplete: async (message, submessage) => {
    // ...
  },
}
```

However, with Safari (iOS), I noticed some Onfido errors in the console:
```
[Error] Trying to call enumerateDevices from an insecure document.
[Error] Trying to call enumerateDevices from an insecure document.
[Error] Trying to call enumerateDevices from an insecure document.
[Error] Failed to load resource: The operation couldn't be completed. Software caused connection abort
[Error] Trying to call enumerateDevices from an insecure document.
...
```

**Comment by stefaniacardenas** [comment] 2019-07-09 13:58
Are you using `http`? You should be using `https` (also on localhost) when using any camera related feature. Let me know if using `https` fixes the issue

**Comment by ctrlaltdylan** [comment] 2019-07-09 16:41
Just to add what evidence I have to @antoinelame's report. This issue has been happening on our HTTPS enabled local, QA and production environments with common devices such as the Macbook Pro, iPhone 8 running Chrome and Safari. I'll provide more user agent information if I can get better details.

**Comment by antoinelame** [comment] 2019-07-10 08:37
Concerning Safari 12.1 (iOS), indeed it was because the use of `http` instead of `https`.

Finally, in our case it works well for:
- Chrome (Desktop and Android)
- Safari (Desktop and iOS)
- Firefox (Desktop)

And as excepted, it doesn't work for:
- Chrome (iOS)

Thank you for your help @stefaniacardenas. I hope in the future, Chrome for iOS will support `getUserMedia`.

**Comment by stefaniacardenas** [comment] 2019-07-15 15:21
Hi @antoinelame, I'm glad you were able to get it working. It seems like the issue you and @ctrlaltdylan have is slightly different. I will close this issue as solved. @ctrlaltdylan I will keep #719 open and post any update regarding improving the flow for `uploadFallback: false` there.

**Closed by stefaniacardenas** 2019-07-15 15:21 UTC

**Comment by TalMat** [comment] 2023-03-18 19:03
2023 and this feature is still not working with Chrome on Android or Windows 10, in my case at least. I'm honestly not sure why you shipped this feature. I'm sure Affirm would be entirely distraught to hear how poorly this works, and find what it is doing to their market.

**Comment by warrenseine** [comment] 2023-03-18 20:30
Hey @TalMat, you're commenting on a closed issue from 2019. If you've got an issue with the Face step on Chrome for Android or Windows, feel free to open a new issue. I can assure you that cameras are properly detected on both.

**Comment by TalMat** [comment] 2023-03-19 14:20
Hey @warrenseine, it's unprofessional to simply deny something isn't working, and to give false assurances to save face. It's not my issue to open, though, since it's a problem with Affirm using onfido. Please refrain from simply saying "it works on my machine" more or less and actually look into it.

**Comment by Fedupwastedtime** [comment] 2023-06-14 10:56
Unfortunately I have the same issue. I use chrome on my android Sony Experia which is only 3yrs old. It's updated Chrome and I had to download a lense to use the QR code Onfino for my document but then for the selfie it refused me saying camera not recognised, or camera banned. I must have tried this about 20 times, so they probably think I'm doing something bad. I'm not super whizz at computer but I think this Onfino is definately not user friendly. I really need to fulfill this document and  selfie. I could cry.

**Comment by TalMat** [comment] 2023-06-14 19:38
> Unfortunately I have the same issue. I use chrome on my android Sony Experia which is only 3yrs old. It's updated Chrome and I had to download a lense to use the QR code Onfino for my document but then for the selfie it refused me saying camera not recognised, or camera banned. I must have tried this about 20 times, so they probably think I'm doing something bad. I'm not super whizz at computer but I think this Onfino is definately not user friendly. I really need to fulfill this document and selfie. I could cry.

Careful. They'll mark your comment as spam, for calling out how unhelpful they're being with their own product.

**Comment by warrenseine** [comment] 2023-06-14 20:03
@TalMat I won't as long as we keep it respectful.

@Fedupwastedtime I'll repeat my previous comment: you're commenting on a closed issue from 2019. If you've got an issue with the Face step on Chrome for Android, feel free to open a new issue. Your experience may be similar, but it's likely a difference issue. However, this repository is intended for developers and integrators, not users. You should ideally raise this problem with the service that uses Onfido, so they can provide us with the necessary details.

**Comment by TalMat** [comment] 2023-06-15 06:53
> I can assure you that cameras are properly detected on both.

**Comment by warrenseine** [comment] 2023-06-15 10:54
Android and Windows are our main platforms. Cameras are detected on these platforms. In no way I'm assuming it works for you or @Fedupwastedtime, I'm simply asking you to create a new issue related to _your_ situation. And as we both said, it should be reported by the team that uses Onfido. For your case @TalMat, did you raise an issue with Affirm?

**Comment by TalMat** [comment] 2023-06-15 18:21
Yes. If I remember correctly, this issue is well after I'd been redirect into Onfido's territory. It was directly not recognizing access to the camera on an android phone and windows machine both. I made it into the process fine, but when it continued failing after troubleshooting, resetting various permissions, and giving them all the version info for android, windows, and chrome, they simply marked me as verified and called it a day.

**Comment by Fedupwastedtime** [comment] 2023-06-15 20:44
I've just bought a new mobile android phone in the hope that this issue of
ID document followed by selfie is accomplished.
After doing every troubleshoot it would not do that selfie. Perhaps it's to
do with the Operating System, my new  Android is Op.System 12 which is the
latest, my other phone was Op.System 9. So I will find out tomorrow when I
do it. Perhaps software is leaving hardware behind.
Will come back and post.

**Comment by GoldProto** [comment] 2023-07-20 05:52
I just today replicated this issue as well as I tried to help two different users obtain financing through Affirm which uses Onfido's ID verification services. 
I was using 2 different Samsung s9+ devices, fully updated Android on one device. Enabled camera and storage permissions for every browser I could find on the phones.  Changed default browsers and tried one by one. 
Still had the issue of camera not detected/enabled for this browser. 
Was not able to proceed with Affirm financing - had to buy product full price. 

I am aware this is a closed issue (and there are other closed very similar issues), but users are still experiencing this problem as I've seen posts on reddit asking for help also. 

Just thought the Devs would appreciate some feedback.

**Comment by Fedupwastedtime** [comment] 2023-07-20 18:06
Thanks for that. Well, after all the mucking about I did and still did not
work, I bought a new phone which has the latest
operating system. So, I conclude it has to be the latest operating system
or won't work. My system is 12 but the  previous
phone was a 9. I really do think they need to stipulate this on the site.
Everyone wasting time on it is pure frustration and money
as well as not being very good for the company name.
