### ISSUE TITLE
SDK Error Occurs when Replaying Selfie Video, preventing user from verifying themselves

### ISSUE THREAD

**Issue by AmruthPillai** [onfido/onfido-sdk-ui#1638] opened 2021-11-29 12:07 UTC
### What was the expected behaviour?

Our customers use Onfido to verify themselves through the SDK. Once they are done with shooting the selfie video, at the stage where the video is displayed to the user to be replayed, the SDK crashes and causes our app/flow to crash in the process.

### What happened instead?

The video is expected to play as normal, and if not, should at least allow the user to continue with the verification process.

### Version info:

- Onfido SDK: 6.15.1-LTS
- OS: iOS 15.1
- Browser: Mobile Safari 15.1
- Device: iPhone
- Framework or relevant dependencies: React

### Steps to reproduce:

Seems to happen just with iOS on Safari/Chrome, looks like a codec issues from our initial research, as we received these errors:

![Screenshot 2021-11-23 at 4 29 27 PM](https://user-images.githubusercontent.com/1134738/143865248-11dca272-8c4c-4e88-823d-3b77889f482f.png)
![Screenshot 2021-11-23 at 4 29 10 PM](https://user-images.githubusercontent.com/1134738/143865255-70ec7b0f-b0f9-4fd6-a389-b91ba292d0b7.png)
![Screenshot 2021-11-23 at 4 28 58 PM](https://user-images.githubusercontent.com/1134738/143865258-8a5354b4-ca19-4097-a6e5-e9d35c1ea595.png)

**Comment by AmruthPillai** [comment] 2021-12-27 07:33
Bumping this to get some eyes on the issue. This is still happening, even after having upgraded to v6.16.0

**Comment by zoeradkani** [comment] 2022-06-21 09:52
Could not reproduce in later versions. @AmruthPillai going to close the issue, please try to upgrade your SDK to a later version.

**Closed by zoeradkani** 2022-06-21 09:52 UTC
