### ISSUE TITLE
wpt

### ISSUE THREAD

**Issue by rpellerin** [onfido/onfido-sdk-ui#656] opened 2019-05-09 16:33 UTC
Hi,
Regarding `wpt` being pulled from Github, could you maybe inline this package instead of relying on Github?
Thank you

**Comment by rfreitas** [comment] 2019-05-23 09:17
it's a good suggestion. Here https://github.com/onfido/onfido-sdk-ui/issues/646#issuecomment-490533109 @davityavryan suggested to switch to https/tar. Would that be okay with you?

**Comment by kopijunkie** [comment] 2019-07-08 15:27
Hi @rpellerin 

FYI the PR to switch to https/tar mentioned above has been merged and released.

**Comment by rpellerin** [comment] 2019-07-08 15:44
Great news! Thanks a lot!

**Comment by rpellerin** [comment] 2019-07-09 08:36
Hi guys,
I can see that `wpt` is still part of `package.json` here https://github.com/onfido/onfido-sdk-ui/blob/master/package.json#L135
Didn't you see you'd moved away from it?

**Comment by rpellerin** [comment] 2019-07-09 08:41
I was suggesting to inline the code of wpt instead of having to rely on a github URL.

**Comment by agaryen** [comment] 2019-07-09 08:44
@kopijunkie: Our build setup is failing atm because of some integrity problem with the wpt dependancy:
``https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz: Integrity check failed for “wpt” (computed integrity doesn’t match our records, got “sha1-kNn2GIQPtDWrKGOlKWV63vq1Shs=“)`

**Comment by alexbaulch** [comment] 2019-07-09 08:48
My team is also experiencing the above issue, we have downgraded to 5.2.1 to get our builds working.

**Comment by ocZio** [comment] 2019-07-09 08:54
@alexbaulch 

Have you tried to turn it off and on again?

**Comment by ocZio** [comment] 2019-07-09 08:55
Windows vista is the issue I think

**Comment by ocZio** [comment] 2019-07-09 09:23
@thomasharper uses windows vista.

**Comment by ocZio** [comment] 2019-07-09 09:48
The file 

https://github.com/Woopra/js-client-tracker/archive/v5.1.19.tar.gz

Has the following sha512 hash

855bfe3722d5a62508dc50dbf2173a75f2e604fa3e65a09bc7574aafef0caa94195d88d0de571ad90b986ee2e5596b6ef79dd3aebb2ba8ec76b867bfe3aae472  v5.1.19.tar.gz


Which converting to BASE64 yields to 

`hVv+NyLVpiUI3FDb8hc6dfLmBPo+ZaCbx1dKr+8MqpQZXYjQ3lca2QuYbuLlWWtu953TrrsrqOx2uGe/46rkcg==`

instead of 
`RIk7xHxKztd58T642fISQehy6Ht5CuVbrkxuj8zjeMxpVoyQhFREIiCzqeXtRahH+/XzuAVaIFR+L4nUG7lggw==`

Two possible scenarios:

- Commit here is wrong
  https://github.com/onfido/onfido-sdk-ui/pull/670/files
- File got changed on github (less likely)

I would suggest to amend the pakage-lock.json and ensuring the correct hash is set.

@ThomasHarper don't use windows Vista.

**Comment by agaryen** [comment] 2019-07-09 10:22
In the meantime, we forked the project and rollbacked the wpt source change: https://github.com/doctolib/onfido-sdk-ui

**Comment by ocZio** [comment] 2019-07-09 10:44
> In the meantime, we forked the project and rollbacked the wpt source change: https://www.npmjs.com/package/@doctolib/onfido-sdk-ui

Really not necessary...

**Comment by alexbaulch** [comment] 2019-07-09 10:48
Issue #726 has full steps for reproducing the issue

**Comment by stefaniacardenas** [comment] 2019-07-09 15:39
Thank you for reporting this. We are looking into it. Will get back to you as soon as we have an update.

**Comment by agaryen** [comment] 2019-07-09 15:43
Thanks. Happy to help if there's anything we can do.

**Comment by davityavryan** [comment] 2019-07-10 21:16
Thanks for the fix. 👍

**Comment by rfreitas** [comment] 2019-07-22 16:15
@rpellerin quoting from here: https://github.com/onfido/onfido-sdk-ui/issues/726#issuecomment-512882121

> Just to clarify, we have removed the tarball installation. At the same time this dependency has been moved to a dev dependency, since this code is actually bundled at compile time. The implication of this last point is that as a client/developer you won't be downloading this dependency, only contributors will have to.

This approach sounds like it's similar to your suggestion of "inline". Let me know if it fixes your usecase.

**Comment by rpellerin** [comment] 2019-07-22 17:06
It does, thank you very much for taking the time to get back to me on this.

**Comment by rfreitas** [comment] 2019-07-22 17:36
great :)

**Closed by rfreitas** 2019-07-22 17:36 UTC
