### ISSUE TITLE
Unexpected behavior with back button?

### ISSUE THREAD

**Issue by ZooeyMiller** [onfido/onfido-sdk-ui#707] opened 2019-06-24 15:56 UTC
Expected behavior:

Clicking the back button in the widget causes the widget itself to go back to the previous state. I.e. I click back from this page:

![image](https://user-images.githubusercontent.com/21139983/60033380-62523800-96a0-11e9-86a8-19f07fdc0944.png)

and am taken back to this page:

![image](https://user-images.githubusercontent.com/21139983/60033419-739b4480-96a0-11e9-9601-8a37fc313b89.png)

Actual behavior:

Clicking the back button from any place in the widget goes back to the page before the widget.

-----

Is this actually the intended behavior? I want to make sure before I put too much time into trying to debug something which might be intentional.

**Comment by ZooeyMiller** [comment] 2019-06-26 08:49
This was resolved by contacting Onfido directly. What I have detailed as expected behaviour is the expected behaviour, and I think the issue is caused by the exact interaction with our application. Closing this issue now but will reply with my solution should I find one.

**Comment by stefaniacardenas** [comment] 2019-06-26 09:29
Hi @ZooeyMiller, thanks for letting us know and apologies for the late reply. It would be good to know what the issue was in case other people have the same issue.

**Comment by jmackie** [comment] 2019-07-03 13:49
On further investigation it seems to be the use of the DOM history api (via [`history/createBrowserHistory`](https://github.com/onfido/onfido-sdk-ui/blob/master/src/components/Router/index.js#L4)] that is interacting badly with our application routing. Modifying the sdk code to import the `createMemoryHistory` constructor resolves our issue.

Would it be possible to either: 

- Use `createHistory` from `history/createMemoryHistory` or
- Make this import configurable in some way

Many thanks!

**Comment by ZooeyMiller** [comment] 2019-07-12 08:20
In light of the resolution and comment @jmackie has made above, I'm reopening this issue to try to give it visibility.

**Comment by stefaniacardenas** [comment] 2019-07-15 16:09
Hi, I have created a ticket in our system to investigate the best solution to fix the incorrect history behaviour. I will keep this issue open and post any updates here. Thanks @ZooeyMiller and @jmackie for reporting it.

**Comment by saidkholov** [comment] 2020-03-20 12:21
I am experiencing the same issue. Any updates?

**Comment by samputer** [comment] 2020-05-04 10:15
Also experiencing the same issue. I can confirm that modifying the SDK's import as per @jmackie's suggestion to use `createMemoryHistory` resolves the problem, however we would prefer to not have to modify library code. Do you have any likely timeframe in mind for resolving this @stefaniacardenas ? Otherwise, the SDK works well. Thanks!

**Comment by stefaniacardenas** [comment] 2020-06-16 10:21
Hi, this issue has been fixed in version [5.10.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/5.10.0). I will close this issue now. Thanks for reporting it.

**Closed by stefaniacardenas** 2020-06-16 10:21 UTC
Labels: in-backlog

**Comment by mattsputnikdigital** [comment] 2022-09-01 09:54
This issue is happening in 6.18.0 where the onfido ui is interfering with the React Router

**Comment by aqadir-dev** [comment] 2022-12-08 10:39
try this
 `useMemoryHistory: true`

**Comment by thexpand** [comment] 2023-08-22 18:10
`useMemoryHistory: true` did the trick for me. I'm running a React application based on Next.js 13 (with the appDir) and it was the only way it didn't bug the Next router. Thanks, @aqadir-dev!
