### ISSUE TITLE
Add basic CSS customization

### ISSUE THREAD

**Issue by ConnerNovicki** [onfido/onfido-sdk-ui#845] opened 2019-11-01 18:36 UTC
I would love to be able to customize the primary color of the UI. This would update:
- Buttons
- Borders
- Upload icon color

Other CSS customization features would be nice, but this is all I need for now :)

**Comment by kopijunkie** [comment] 2019-11-04 16:34
Hi @ConnerNovicki 

We have plans to make customising the SDK's UI elements easier for integrators on our roadmap, but not confirmed ETA as yet. For now, you can customise the style to fit your web app/site by overriding the CSS classes for the 3 UI elements you need:

* Buttons: `.onfido-sdk-ui-Button-button-primary`
* Borders: `.onfido-sdk-ui-Modal-inner` (overall SDK container border)
* Upload icon color: `.onfido-sdk-ui-Uploader-identityIcon, .onfido-sdk-ui-Uploader-faceIcon` (**Note:** the icon is actually a SVG image set as the background image)

Please note that future releases might introduce CSS changes that could potentially affect your customisations and require an update.

Let me know if you need any further help.

**Comment by bandyguy** [comment] 2020-06-12 15:00
@kopijunkie Any updates on where this has fallen in your roadmap?

**Comment by stefaniacardenas** [comment] 2020-07-09 14:03
Hi, we are planning to work on this next quarter.

**Comment by aguetat** [comment] 2020-08-11 12:35
Hello,
As it is said we can customize the onfido interface by overloading the css classes.
Is there a trick to customize the onfido mobile interfaces (document scanning interfaces), please ?
Thanks

**Comment by stefaniacardenas** [comment] 2020-08-24 12:43
Not at the moment, unfortunately. We will implement a solution for that as part of the customisation feature.

**Comment by kopijunkie** [comment] 2021-03-22 17:00
Hi @ConnerNovicki @aguetat 

FYI in the upcoming release 6.7.0 we will be introducing UI customisation options that will include the ability to customise the Buttons, Borders & Icons' circle background color. You can see a preview of what customisation options are available in the [README](https://github.com/onfido/onfido-sdk-ui/blob/8f28a40141efc2d50edc6798c6ec1ba86c7f995f/README.md) on the release PR #1384 branch.

Note that if you are currently customising your SDK integration by overriding the CSS classes, this might be a breaking change due to some class name changes.

This also includes support for applying the customization on the SDK's UI on mobile browsers when a user is on the Cross Device flow on their mobile devices.

**Comment by kopijunkie** [comment] 2021-03-29 15:35
@ConnerNovicki @bandyguy @aguetat We just released the UI customisation options feature mentioned above last week. 
Please upgrade to [**6.7.1**](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.7.1) as there was a bug reported in the initial release [6.7.0](https://github.com/onfido/onfido-sdk-ui/releases/tag/6.7.0).

I'll close this ticket now. But feel free to raise a ticket should there be any further issues or features you might like to see on the Web SDK.

**Closed by kopijunkie** 2021-03-29 15:35 UTC
Labels: feature-request, to-be-released
